x<-read.csv("C:/Users/Cheng/Documents/Coursera/household_power_consumption.txt",na.strings = "?",colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),sep=";")
x$Date<-as.Date(x$Date,"%d/%m/%Y")
y<-x[x$Date %in% as.Date(c("2007-02-01","2007-02-02"),"%Y-%m-%d"),]
y$Time<-strptime(paste(y$Date,y$Time),"%Y-%m-%d %H:%M:%S")
png(filename= "Plot3.png", width = 480, height = 480)
plot(y$Time,y$Sub_metering_1,type="l",xlab = "", ylab="Energy sub metering")
lines(y$Time,y$Sub_metering_2,col="red")
lines(y$Time,y$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1) ,col = c("black","red","blue"))
dev.off()